name: Build
on:
  workflow_dispatch:

jobs:
  base-them:
    runs-on:
      group: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dev dependencies
        run: |
          pnpm install
      - name: Build theme
        run: |
          pnpm --theme=base build
      - name: Install unzip
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
      - name: Unzip theme
        run: |
          mkdir -p tmp/theme && unzip base/theme.zip -d tmp/theme
      - name: Archive theme
        uses: actions/upload-artifact@v4.3.4
        with:
          name: theme
          path: |
            tmp/theme

